spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: jhkafka
          content-type: application/json
        output:
          destination: jhkafka
          content-type: application/json
  datasource:
    url: jdbc:h2:file:./target/h2db/db/example;DB_CLOSE_DELAY=-1
    username: example
    password:
    driver-class: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
      hibernate:
        ddl-auto: update
camunda:
  bpm:
    admin-user:
      password: demo
      id: demo
      first-name: Demo
      last-name: Demo
      email: info@reunico.com
